Repository vaadin/vaadin-dialog, pull requests merged in 2018-09, with the labels that each got.

#42 Propagate theme attribute to internal overlay.
  .travis.yml
  bower.json
  demo/dialog-basic-demos.html
  demo/index.html
  src/vaadin-dialog.html
  test/vaadin-dialog_test.html
Labels: backlog

#107 Manual rendering of the content
  bower.json
  src/vaadin-dialog.html
  test/vaadin-dialog_renderer-test.html
Labels: in review

#117 Fix renderer use in the demos [skip ci]
  demo/dialog-basic-demos.html
Labels: in review

#118 Improve renderers docs [skip ci]
  demo/dialog-basic-demos.html
  src/vaadin-dialog.html
Labels: in progress
